export const GET_ALL_PRODUCTS_DATA = 'GET_ALL_PRODUCTS_DATA';
export const GET_FOCUSED_PRODUCT_DATA = 'GET_FOCUSED_PRODUCT_DATA';
export const SET_FOCUSED_PRODUCT_DATA = 'SET_FOCUSED_PRODUCT_DATA';
export const SET_SYNTH_SCUSD_AMOUNT = 'SET_SYNTH_SCUSD_AMOUNT';
export const SET_ASSET_TOTAL_VALUE = 'SET_ASSET_TOTAL_VALUE';
export const SET_ALL_ASSETS = 'SET_ALL_ASSETS';
export const SET_REFRESH ='SET_REFRESH';
